version: 1
builder:
  configs:
    - documentation_targets: [Numerix, VectorModule, MatrixModule, ShapedArrayModule]
      custom_documentation_parameters: [--additional-symbol-graph-dir ".symbolgraph"]
