name: Run linter checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linter:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Install swiftlint
      run: brew install swiftlint
    - name: Run linter checks
      run: swiftlint
