name: Generate symbol graph
on:
  push:
    branches: ["main"]

jobs:
  symbol-graph-gen:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Select xcode version
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app
    - name: Generate symbol graph
      run: |
           swift build \
                -Xswiftc -emit-symbol-graph \
                -Xswiftc -emit-symbol-graph-dir -Xswiftc .symbolgraph/
    - name: Stage .symbolgraph
      run: git add .symbolgraph
    - name: Commit changes
      run: git commit -m "[🤖 Auto] update .symbolgraph"
    - name: Push changes
      run: git push
