name: Generate symbol graph
on:
  push:
    branches: ["main"]

jobs:
  symbol-graph-gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Swiftly (and Swift)
      run: |
          curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz && \
          tar zxf swiftly-$(uname -m).tar.gz && \
          ./swiftly init --quiet-shell-followup --verbose --assume-yes && \
          . ~/.local/share/swiftly/env.sh && \
          hash -r
    - name: Log Swift version
      run: swift --version
    - name: Generate symbol graph
      run: |
           swift build \
                -Xswiftc -emit-symbol-graph \
                -Xswiftc -emit-symbol-graph-dir -Xswiftc .symbolgraph/
    - name: Stage .symbolgraph
      run: git add .symbolgraph
    - name: Commit changes
      run: git commit -m "[🤖 Auto] update .symbolgraph"
    - name: Push changes
      run: git push
