name: Run swift tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Select xcode version
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app
    - name: Build the package
      run: swift build
    - name: Run tests with swift
      run: swift test
